package org.freaknowledge

rule "Important processes must have messages"

    when
        $p : TestProcess(message == null, important == true)

    then
    
      Failure failure = new Failure();
      
      Object fact = insert(failure);

      failure.setFactHandle();
end

rule "Start process"

    when
        $p : TestProcess(message != null, important != true)

    then
    
        System.out.println($p.getFactHandle());
end


